### ISSUE TITLE
Release API URL change

### ISSUE THREAD

**Issue by tomasbedrich** [honzajavorek/fiobank#30]
Hi, [this](https://github.com/honzajavorek/fiobank/commit/121bc872d5e1404f19f44865fa3bdd108d3b59a3) needs to be released. Thx in advance :)

**Comment by honzajavorek** [comment]
It's on my list. Doing my best regarding my free time. AFAIK we still have several months to go. Or is it causing some immediate issues?

**Comment by tomasbedrich** [comment]
Sure, I just wanted to make sure you are aware. No immediate issues right now. Just that the downstream apps also need some time to migrate.

**Comment by honzajavorek** [comment]
That’s a good point!

**Comment by honzajavorek** [comment]
Should be done!
