### ISSUE TITLE
Avoid HTTP 409

### ISSUE THREAD

**Issue by honzajavorek** [honzajavorek/fiobank#5]
https://twitter.com/jakubkulhan/status/380413916175560704 by @jakubkulhan

**Comment by Visgean** [comment]
Not really undocumented: http://www.fio.cz/docs/cz/API_Bankovnictvi.pdf section 8.2:
Nedodržujete minimální interval 30 sekund mezi dotazy na daný token (bez ohledu na typ formátu).
